import {
  DashboardSquare01Icon,
  UserMultiple02Icon,
  ClipboardIcon,
  Alert02Icon,
  Route01Icon,
  Car03Icon,
  IdentificationIcon,
  PetrolPumpIcon,
  CheckListIcon,
  Shield01Icon,
  ArrowRightDoubleIcon,
  AnalyticsUpIcon,
  Notification03Icon,
  Search01Icon,
  Calendar03Icon,
  Mail01Icon,
  SmartPhone01Icon,
  LockPasswordIcon,
  Logout01Icon,
  Settings02Icon,
  UserIcon,
  GlobalIcon,
  Menu02Icon,
  Cancel01Icon,
  PlusSignIcon,
  Download01Icon,
  Edit02Icon,
  Delete01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowDown01Icon,
  Tick02Icon,
  AlertCircleIcon,
  Clock01Icon,
  Location01Icon,
  StarIcon,
  Time01Icon,
  File01Icon,
  Sun01Icon,
  Moon01Icon,
  CloudIcon,
  HelpCircleIcon,
  WorkflowSquare01Icon,
  Wrench01Icon,
  Upload01Icon,
  ShoppingCart01Icon,
  Store01Icon,
  Invoice01Icon,
  DeliveryBox01Icon,
  Money01Icon,
} from "hugeicons-react";

import type { ComponentType, SVGProps } from "react";

type IconComp = ComponentType<SVGProps<SVGSVGElement> & { size?: number; strokeWidth?: number; variant?: string }>;

const map: Record<string, IconComp> = {
  dashboard: DashboardSquare01Icon,
  users:     UserMultiple02Icon,
  clipboard: ClipboardIcon,
  alert:     Alert02Icon,
  route:     Route01Icon,
  car:       Car03Icon,
  idcard:    IdentificationIcon,
  fuel:      PetrolPumpIcon,
  checklist: CheckListIcon,
  shield:    Shield01Icon,
  handover:  ArrowRightDoubleIcon,
  chart:     AnalyticsUpIcon,
  bell:      Notification03Icon,
  search:    Search01Icon,
  calendar:  Calendar03Icon,
  mail:      Mail01Icon,
  phone:     SmartPhone01Icon,
  lock:      LockPasswordIcon,
  logout:    Logout01Icon,
  settings:  Settings02Icon,
  user:      UserIcon,
  globe:     GlobalIcon,
  menu:      Menu02Icon,
  close:     Cancel01Icon,
  plus:      PlusSignIcon,
  download:  Download01Icon,
  edit:      Edit02Icon,
  trash:     Delete01Icon,
  left:      ArrowLeft01Icon,
  right:     ArrowRight01Icon,
  up:        ArrowUp01Icon,
  down:      ArrowDown01Icon,
  check:     Tick02Icon,
  alertCircle: AlertCircleIcon,
  clock:     Clock01Icon,
  location:  Location01Icon,
  star:      StarIcon,
  time:      Time01Icon,
  file:      File01Icon,
  sun:       Sun01Icon,
  moon:      Moon01Icon,
  cloud:     CloudIcon,
  help:      HelpCircleIcon,
  workflow:  WorkflowSquare01Icon,
  wrench:    Wrench01Icon,
  upload:    Upload01Icon,
  cart:      ShoppingCart01Icon,
  store:     Store01Icon,
  invoice:   Invoice01Icon,
  box:       DeliveryBox01Icon,
  money:     Money01Icon,
};

interface Props {
  name: keyof typeof map | string;
  size?: number;
  strokeWidth?: number;
  className?: string;
}

export function Icon({ name, size = 18, strokeWidth = 1.6, className }: Props) {
  const Comp = (map as Record<string, IconComp>)[name] ?? HelpCircleIcon;
  return <Comp size={size} strokeWidth={strokeWidth} className={className} />;
}
